- hosts: all
  vars:
    user: ubuntu
    group: ubuntu
    limits_user: ubuntu
    homedir: /home/ubuntu
  become: true
  gather_facts: true
  roles:
    - title: toolchain
      vars:
        name: golang
    - title: system-package
      vars:
        name: neofetch
        version: latest
    - title: system-package
      vars:
        name: htop
        version: latest
    - title: system-package
      vars:
        name: tree
        version: latest
    - title: system-package
      vars:
        name: cowsay
        version: latest    
    - title: folder
      vars:
        path: /opt/temp
    - title: binary
      vars:
        url: https://s3.aws.com/
        dest: /opt/binary
