- component: label
  title: Name
- component: dropdown
  default:
  options:
    - golang
    - java
    - nodejs
    - php
    - python
  register: name
- component: label
  title: Verion
- component: input
  default: latest
  register: version
- component: label
  title: Test
- component: input
  default:
  register: test
